# Workflow para deploy do Jekyll e execução do Gabi-GPT

name: Deploy Jekyll com GitHub Pages e Executar Gabi-GPT

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build do Jekyll
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build com Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Job de execução do Gabi-GPT
  run-gabi-gpt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Instalar dependências
        run: npm install
      - name: Executar Gabi-GPT
        run: node gabi-gpt.js
        env:
          API_GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}  # Passa o segredo para o script

  # Job de deployment para GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4