name: Deploy Site to GitHub Pages

on:
  push:
    branches:
      - main  # A branch que você usa para deploy, neste caso 'main'
  pull_request:
    branches:
      - main  # Pode ser ajustado para outras branches, se necessário

jobs:
  deploy:
    runs-on: ubuntu-latest  # Ambiente de execução (Ubuntu mais recente)

    steps:
      # Passo 1: Checar o código fonte
      - name: Checkout code
        uses: actions/checkout@v2

      # Passo 2: Publicar no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.1.2
        with:
          branch: gh-pages  # Branch onde o site será publicado
          folder: .  # A pasta que contém os arquivos a serem publicados. Pode ser '.' ou 'dist', dependendo de onde os arquivos estão
          token: ${{ secrets.API_GITHUB_TOKEN }}  # Utiliza o seu token personalizado
